import { Card } from './types/card'; // Adjust the import path as necessary

export const cards: Card[] = [
    { id: "001", name: "Contemplation Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "002", name: "Bamboo Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "003", name: "Carnival Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "004", name: "Chef Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "005", name: "Chub, Very Late for Action", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "006", name: "Chitchatella Unleashed", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "007", name: "Inceptious Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "008", name: "Inspting Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "009", name: "Kingferling Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "010", name: "Mobbing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "011", name: "Peace Out Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "012", name: "Popcorn Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "013", name: "Red Map Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "014", name: "Red Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "015", name: "Ribbon-Dancing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "016", name: "Risk-Taking Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "017", name: "Royal Black Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "018", name: "Screaming Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "019", name: "Serene Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "020", name: "Striking Swordsman Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "021", name: "A Drop to Abandon", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "022", name: "Again, Again", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "023", name: "Bearish Sentiment", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "024", name: "Best Seats in the House", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "025", name: "Grow Together", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "026", name: "Have an Encore", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "027", name: "Heads I Love, Tails You Lose", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "028", name: "Hit the High Note", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "029", name: "Not a Bad Argument", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "030", name: "Put on a Show", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "031", name: "Rush to the Bath", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "032", name: "Sunbeam's Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "033", name: "Trust Fall", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "034", name: "Use Whoopee Cushion", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "035", name: "Dashing Swordsman Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "036", name: "Dogfighting Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "037", name: "Esteemed Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "038", name: "Flying Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "039", name: "Hyper Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "040", name: "Jubilant Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "041", name: "Lucky Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "042", name: "Mysterious Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "043", name: "Napenguin, Legendary Host", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "044", name: "Paper Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "045", name: "Penguin of the Falling Leaves", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "046", name: "Penguin Who Doesn't Mind Goodbyes", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "047", name: "Penguin Who Night Bring a Plus One", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "048", name: "Penguin Who Spills the Tea", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "049", name: "Penguin Who Zooms", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "050", name: "Penguin Who's Late to the Party", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "051", name: "Shocking Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "052", name: "Put-Strong Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "053", name: "Rock Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "054", name: "Scissors Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "055", name: "Shapenguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "056", name: "Phopeos, Who Stands Alone", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "057", name: "Shy Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "058", name: "Yellow Mega Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "059", name: "Yellow Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "060", name: "Buddy Up", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "061", name: "Cross the Yellow Plains", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "062", name: "Put Your Flippers in the Air", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "063", name: "Stop to Reset", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "064", name: "Not Your Keys", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "065", name: "Prepare for a Wild Night", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "066", name: "They're Twins", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "067", name: "What a Tweet!", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "068", name: "Yum Yum", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "069", name: "Balanced Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "070", name: "Blossoming Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "071", name: "Corticus Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "072", name: "Flower-Arranging Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "073", name: "Green Mega Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "074", name: "Green Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "075", name: "Karate Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "076", name: "Lonely Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "077", name: "Ornate Swordsman Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "078", name: "Penguin in Color", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "079", name: "Penguin Who is the Garden", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "080", name: "Penguin With Garden Grace", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "081", name: "Penguin With Giant Mystique", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "082", name: "Koi Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "083", name: "Poeticela Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "084", name: "Sir Velocitist", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "085", name: "Romeo Who Booms", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "086", name: "Sketching Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "087", name: "Sliding Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "088", name: "Straygang Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "089", name: "Success Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "090", name: "Window-Watching Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "091", name: "Chisel Your Stone", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "092", name: "Clean Up Good", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "093", name: "Escape in Time", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "094", name: "Everybody Stay Clean", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "095", name: "Got 'Em!", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "096", name: "Lost in the Sauce", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "097", name: "Raid the Snacks", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "098", name: "Love Some the Penguins", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "099", name: "Send Off", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "100", name: "Too Cool for School", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "101", name: "Walk the Runway", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "102", name: "You Dropped This", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "103", name: "Bashful Swordsman Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "104", name: "Blue Mega Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "105", name: "Blue Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "106", name: "Battle Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "107", name: "Ceremonial Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "108", name: "Amazing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "109", name: "Drawing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "110", name: "Dragonnder Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "111", name: "Fast Finding Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "112", name: "Frosty the Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "113", name: "Jealous Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "114", name: "Miss Chief, Keeper of Keys", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "115", name: "Miss Place, Forgetter of Things", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "116", name: "Politics Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "117", name: "Penguin Guard in Fishing Line", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "118", name: "Penguin Who Explores the Best", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "119", name: "Penguin Who's OK", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "120", name: "Penguin With Home", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "121", name: "Portfolio Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "122", name: "Purple Chief Who's Super Cool", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "123", name: "Sneaky Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "124", name: "Total Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "125", name: "Waterfall Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "126", name: "Bedtime Story", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "127", name: "Bridge With Lager Zero", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "128", name: "Cool Story Bro!", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "129", name: "Don't Trust Verity", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "130", name: "Ingenious Ideas", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "131", name: "Keep Digging", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "132", name: "Questionable Methods", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "133", name: "Send It Too Hard", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "134", name: "Spring a Leak", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "135", name: "Three Wise Penguins", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "136", name: "Unlikely Friends", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "137", name: "Absent-Minded Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "138", name: "Abstract Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "139", name: "Ambitious Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "140", name: "Ascending Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "141", name: "Bruno, PhD Candidate", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "142", name: "Bubbly Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "143", name: "Bubbles, the Great and Powerful", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "144", name: "Bubbles, Who is the Stars", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "145", name: "Charming Swordsman Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "146", name: "Crossing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "147", name: "Demolition Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "148", name: "Galaxy Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "149", name: "Gatehopper Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "150", name: "Penguin With a Flag", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "151", name: "Grateful Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "152", name: "Penguin Who Breaks the Fourth Wall", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "153", name: "Penguin Who Carries the Ring", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "154", name: "Penguin Who Runs Into It", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "155", name: "Prosperous Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "156", name: "Purple Mega Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "157", name: "Purple Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "158", name: "Space Quest Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "159", name: "Unmatted Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "160", name: "Adventure Squad", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "161", name: "Change Perspective", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "162", name: "Chase Your Dream", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "163", name: "Gather Together", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "164", name: "Have a Philosophical Debate", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "165", name: "One With History", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "166", name: "Overwhelm With Knowledge", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "167", name: "Sick Fnaf", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "168", name: "Spring Break", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "169", name: "Study All Night", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "170", name: "Wait", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "171", name: "Zen Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "172", name: "Ryun-Tying Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "173", name: "Rushing Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "174", name: "Inquisitive Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "175", name: "Immortal Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "176", name: "Primo Wizard Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "177", name: "Penguin With a Rod of His Own", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "178", name: "Teleporter Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "179", name: "Searching Penguin", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "180", name: "Supporting Friend", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "181", name: "Change of Lighthouse Color", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "182", name: "Cookies of Truth", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "183", name: "Dummy Thicc Disco Ball", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "184", name: "Running Story", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "185", name: "Lager High Technology", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "186", name: "City of Hopes", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "187", name: "Silent Stone Globe", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "188", name: "The End of the Rainbow", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "189", name: "Too Much Caffeine", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "190", name: "Wizard Cup", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "191", name: "Bounce Power Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "192", name: "Catapultaha Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "193", name: "Freezing Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "194", name: "Hot Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "195", name: "Pudge Man Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "196", name: "Rod of Camaraderie", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "197", name: "Umbrella Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "198", name: "Rod of Racing Shoes", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "199", name: "Trampoline Rod", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "200", name: "Rod of Charming Melodies", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "201", name: "Barrel Hijacketes", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "202", name: "Promo/Gift code", checks: { nonfoil: false, foil: false, sketch: false } },
    { id: "203", name: "Promo/Gift code", checks: { nonfoil: false, foil: false, sketch: false } },
];
